[parity]
chain = "demo-spec.json"
base_path = "/tmp/parity-user"
[network]
port = 30302
[rpc]
port = 8542
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
cors = ["http://remix.ethereum.org"]  # allow remix to access this node
[websockets]
port = 8452
[account]
password = ["2/user.pwd"]
unlock = ["0x004ec07d2329997267ec62b4166639513386f32e"]